// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCb5ZhqnYB3mazV_iXr2A8qdIB9D4YxRd4',
//     appId: '1:881721831294:web:5217e774ef4e71df7f4d2f',
//     messagingSenderId: '881721831294',
//     projectId: 'saturday-a10d6',
//     authDomain: 'saturday-a10d6.firebaseapp.com',
//     storageBucket: 'saturday-a10d6.appspot.com',
//     measurementId: 'G-NHHN2H9MF8',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDpxKQ_oDADxidM-iUajYIBY5xBZrOmXVM',
//     appId: '1:881721831294:android:5ee8124aff84ff757f4d2f',
//     messagingSenderId: '881721831294',
//     projectId: 'saturday-a10d6',
//     storageBucket: 'saturday-a10d6.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAm8ov_wvvbJBMN0qaDCTfJNpnfbw6R3bQ',
//     appId: '1:881721831294:ios:3b922636003417817f4d2f',
//     messagingSenderId: '881721831294',
//     projectId: 'saturday-a10d6',
//     storageBucket: 'saturday-a10d6.appspot.com',
//     iosBundleId: 'com.example.saturday',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAm8ov_wvvbJBMN0qaDCTfJNpnfbw6R3bQ',
//     appId: '1:881721831294:ios:b4dfbf09e7508b277f4d2f',
//     messagingSenderId: '881721831294',
//     projectId: 'saturday-a10d6',
//     storageBucket: 'saturday-a10d6.appspot.com',
//     iosBundleId: 'com.example.saturday.RunnerTests',
//   );
// }
